ARG BASE_IMAGE=quay.io/pypa/manylinux2014_x86_64

FROM $BASE_IMAGE as build

RUN /opt/python/cp38-cp38/bin/python -m pip install --upgrade -q pip
RUN /opt/python/cp38-cp38/bin/python -m pip install cmake

RUN yum install -y ccache

RUN ccache --set-config max_size=80M
RUN ccache --show-config
