name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Download Microsoft MPI (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-WebRequest https://github.com/Microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisetup.exe -OutFile msmpisetup.exe
          Invoke-WebRequest https://github.com/Microsoft/Microsoft-MPI/releases/download/v10.1.1/msmpisdk.msi -OutFile msmpisdk.msi

      - name: Install Microsoft MPI (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          msmpisetup.exe -unattend -minimal
          msmpisdk.msi /passive
          echo "C:/Program Files/Microsoft MPI/Bin/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install openMPI (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install libopenmpi-dev

      - name: Install openMPI (MacOS)
        if: matrix.os == 'macos-latest'
        run: brew install openmpi

      - name: Configure CMake
        run: cmake -S .  -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: cmake --build build --config Release --target test
