name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      VCPKG_DISABLE_METRICS: 1
      VCPKG_DEPS_JSON: .github/vcpkg.json

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup vcpkg
        id: vcpkg-root
        shell: bash
        run: |
          cd $VCPKG_INSTALLATION_ROOT
          ./vcpkg --version > $GITHUB_WORKSPACE/vcpkg-version.txt
          echo "::set-output name=path::$(echo -E "$VCPKG_INSTALLATION_ROOT" | sed -e 's,\\,/,g')"

      - name: Cache vcpkg
        uses: actions/cache@v2
        id: cache-vcpkg
        with:
          path: ${{ steps.vcpkg-root.outputs.path }}/installed
          key: vcpkg-${{ runner.os }}-x64-${{ hashFiles('vcpkg-version.txt') }}-${{ hashFiles(env.VCPKG_DEPS_JSON) }}
          restore-keys: |
            vcpkg-${{ runner.os }}-x64-${{ hashFiles('vcpkg-version.txt') }}-
            vcpkg-${{ runner.os }}-x64-

      - name: Check if msmpi is installed
        id: check-msmpi
        shell: bash
        run: |
          # When no package is installed, "vcpkg list msmpi" prints a line
          missing=$( $VCPKG_INSTALLATION_ROOT/vcpkg list msmpi | grep -q msmpi; echo $? )
          echo "::set-output name=missing::$missing"

      - name: Downloading MPI
        #if: steps.check-msmpi.outputs.missing == 1
        # URLs copied from https://github.com/microsoft/vcpkg/blob/master/ports/msmpi/portfile.cmake
        shell: powershell
        run: |
            $client = new-object System.Net.WebClient
            $client.DownloadFile("https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisetup.exe", "msmpisetup.exe")
            $client.DownloadFile("https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisdk.msi", "msmpisdk.msi")

      - name: Installing MPI
        #if: steps.check-msmpi.outputs.missing == 1
        shell: cmd
        run: |
            msmpisetup.exe -unattend
            msmpisdk.msi /passive

      - name: Install vcpkg packages
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        shell: bash
        run: |
          $VCPKG_INSTALLATION_ROOT/vcpkg install --debug --triplet x64-windows $(jq -j '.dependencies[] | ., " "' $VCPKG_DEPS_JSON)

      - name: List vcpkg packages
        shell: bash
        run: |
          ls -lR $VCPKG_INSTALLATION_ROOT/installed

      - name: Configure CMake
        run: |
          cmake -B build -S . -DCMAKE_PREFIX_PATH=${{ steps.vcpkg-root.outputs.path }}/installed/x64-windows

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: cmake --build build --config Release --target test
