name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  setop:
    runs-on: ubuntu-latest
    outputs:
      python_version: ${{ steps.generate-matrix.outputs.python_version }}
      build_doc: ${{ steps.generate-matrix.outputs.build_doc}}
      build: ${{ steps.generate-matrix.outputs.build}}
      test: ${{ steps.generate-matrix.outputs.test}}
    steps:
      - uses: actions/setup-python@v2
      - name: Generate Matrix
        id: generate-matrix
        shell: python3 {0}
        run: |
          python_version = ["3.7", "3.8", "3.9"]
          build = { "macos": ["macos-10.15"], "linux": ["ubuntu-latest"], "windows": ["windows-2016"] }
          test = { "macos": ["macos-10.15", "macos-11"], "linux": ["ubuntu-18.04", "ubuntu-20.04"], "windows": ["windows-2016", "windows-2019", "windows-2022"] }
          print(f"::set-output name=python_version::{python_version}")
          print(f"::set-output name=build::{build}")
          print(f"::set-output name=test::{test}")
          print(f"::set-output name=build_doc::true")

  debug:
    needs: [setop]
    strategy:
      matrix:
        os: ["macos-10.15", "macos-11"]
        python-version: ${{ fromJSON(needs.setop.outputs.python_version) }}
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: pip debug
        run: |
          pip debug -v

  test:
    needs: [debug]
    runs-on: ubuntu-latest

    steps:
      - name: if build_doc in step
        if: ${{ needs.setop.outputs.build_doc == 'true' }}
        run: echo "run"

  job-if:
    needs: [debug]
    if: ${{ needs.debug.needs.setop.build_doc == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Start
        run: echo "ok"
  
      - name: Conditional step
        if: ${{ needs.debug.needs.setop.outputs.build_doc == 'true' }}
        run: echo "run"
