name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    env:
      VCPKG_DISABLE_METRICS: 1

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Downloading MPI
        # URLs copied from https://github.com/microsoft/vcpkg/blob/master/ports/msmpi/portfile.cmake
        shell: powershell
        run: |
            $client = new-object System.Net.WebClient
            $client.DownloadFile("https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisetup.exe", "msmpisetup.exe")
            $client.DownloadFile("https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisdk.msi", "msmpisdk.msi")

      - name: Installing MPI
        shell: cmd
        run: |
            msmpisetup.exe -unattend
            msmpisdk.msi /passive

      - name: Restore vcpkg packages
        uses: lukka/run-vcpkg@v6
        id: runvcpkg
        with:
          # The Git commit id of vcpkg to be checked out. This is only needed because we are not using a submodule.
          vcpkgGitCommitId: '5568f110b509a9fd90711978a7cb76bae75bb092'
          vcpkgTriplet: 'x64-windows'
          vcpkgArguments: 'gtest eigen3 boost-log boost-program-options msmpi'
