name: Build doc

on:
  workflow_dispatch:
  workflow_run:
    workflows:
      - "Build"
    types:
      - completed

jobs:
  build-docs:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate
        run: |
          env | grep GITHUB_ | sort
